version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=SmBYWmfaeVyspqfa
      - MYSQL_DATABASE=iot
      - MYSQL_USER=iot
      - MYSQL_PASSWORD=SmBYWmfaeVyspqfa
    ports:
        - "3333/tcp:3306/tcp"
  lorawan-sk-backend:
    build:
      context: .
      dockerfile: Dockerfile-lorawan-sk-backend
    container_name: lorawan-sk-backend
    command: python manage.py runserver 0.0.0.0:8888
    ports:
        - "8888/tcp:8888/tcp"
    links:
      - mariadb
    environment:
      - DB_HOST=mariadb
    depends_on:
      - mariadb
